### ISSUE TITLE
Should there be a start:dev script?

### ISSUE THREAD

**Issue by WillSmithTE** [mcansh/remix-fastify#107]
After running `npx create-remix@latest --template https://github.com/mcansh/remix-fastify/tree/main/example --no-install`, per the README we should run `npm run dev` and `npm run start:dev`. Should there be a `start:dev` script? What am I missing here?

**Comment by mcansh** [comment]
sorry about the confusion, the example README is from the express template before i made any modifications, `npm run dev` is enough, i’ll update the example README in a bit :)

**Comment by WillSmithTE** [comment]
ok great thanks for the clarification
