### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by pedrospj** [mcansh/remix-fastify#111]
I followed the instructions to create a remix project with remix-fastify template but I got an error when I tried to install the dependencies.
The problem is that `@mcansh/remix-fastify` comes with `workspace:*` as version. I tried both `npm install` and `yarn`, but they fail to install due to not recognizing the version (screenshots below). I know the fix is just edit `package.json` and put the version on the lib, but this can be confusing for unexperienced developers who are trying to use this lib.

**npm install**
![image](https://github.com/mcansh/remix-fastify/assets/26507864/5d134f49-d45c-48fa-be39-3bd10198312a)

**yarn**
![image](https://github.com/mcansh/remix-fastify/assets/26507864/7421795c-8b70-4971-bba8-549694a31dac)

The other thing I noticed is that the `isbot` lib is listed as a dependency, but it's not used anywhere in the example code, so I believe it could be removed.
![image](https://github.com/mcansh/remix-fastify/assets/26507864/5885dd99-8a94-450f-92ee-ca821dd8b1c8)

I'd be happy to open a PR to make the changes, let me know what you think.

**Comment by mcansh** [comment]
correct, it’s mentioned in the README that you need to opt out of installing currently and either manually install the package or run `node scripts/preinstall.mjs`, i’d like to fix this, but don’t want to make this package harder to develop on either. 

isbot is a peer dependency as it’s needed by [entry.server](https://remix.run/docs/en/main/file-conventions/entry.server) (which is optional) for sending the entire html response for bots instead of streaming the response (when using defer)

**Comment by pedrospj** [comment]
Oh I get it. In that case, I would suggest that `Quick Start` should come before `Installation` in the README, this confused me a bit. Also, this `preinstall` script could also be mentioned, I just learned about it through your aswer. Another suggestion to the README is to update the link to `example/server.mjs` currently it's pointing to a `server.ts` that doesn't exist.

Thank you for the awsome lib and for taking the time to answer me ❤️

**Comment by pedrospj** [comment]
Reading the Remix docs I just learned about [remix-init](https://remix.run/docs/en/1.19.2/other-api/dev#remix-init),
What do you think about changing tyhe `preinstall.mjs` to `remix.init/index.js`? that way the `package.json` file would be updated and we could allow installation.
I think this would make it easier using this lib.

Let me know what you think, maybe I could help with a PR.

**Comment by mcansh** [comment]
remix i it runs after install, so same issue would occur, looking into switching to using bun as the package manager which would resolve the workspace protocol issue

#112

**Comment by pedrospj** [comment]
Oh ok. What about my suggestions on README? Do they make sense?

**Comment by pedrospj** [comment]
Just saw you fixed it in you PR.

Thanks for answering! Awesome work.

**Comment by mcansh** [comment]
just wanted to circle back and let you know that I've overhauled the example and it now uses an actual version of this package instead of the pnpm `workspace:` protocol which will get updated as this package continues to get updates :)

old example moved to `./playground`

**Comment by pedrospj** [comment]
Thanks for the update!
