### ISSUE TITLE
Posting "application/json" using fetcher not working

### ISSUE THREAD

**Issue by rolanday** [mcansh/remix-fastify#116]
Remix [v.1.18.0](https://github.com/remix-run/remix/releases) added support for JSON/Test submissions. For example:

```
      <button
        onClick={() => {
          fetcher.submit(
            { foo: "bar" },
            {
              method: "POST",
              action: "/test",
              encType: "application/json",
            }
          );
        }}
      >
        test
      </button>
```

For action on same route:
```
export const action = async ({ request }: ActionArgs) => {
  console.log(await request.json());
  return null;
};
```

Works as expected on Express (prints JSON to console):
[/Users/roland/GitHub/public/remix/remix-express](https://github.com/rolanday/remix-express) <== works

However, same client code and action fail when using Remix Fastify adapter:
[/Users/roland/GitHub/public/remix/remix-fastify](https://github.com/rolanday/remix-fastify-post-json-issue) <== fails

Even though shouldn't be needed for Fastify (parses application/json by default), added contentTypeParser to server.mjs anyway but didn't help (but did see the json string being proceeded inside when logged).

**Comment by mcansh** [comment]
seems as though the built in fastify json support is combating the `*` content parsing as adding a log to `fastify.addContentTypeParser("*")` never fires unless you remove the json content parsing

**Comment by rolanday** [comment]
As mentioned, I explicitly added "application/json" as content type parser in hopes might address the issue, even though it shouldn't (and it didn't). The repo shared was created using `npx create-remix@latest --template https://github.com/mcansh/remix-fastify/tree/main/example --no-install` with just the small demonstrating the failed use case. I was able to work around posting the "remix way" (i.e., formdata) but I ran into readstream errors authenticating w/ remix-auth so I'm afraid I needed to revert back to Express. Loved the perf seeing w/ Fastify though.

**Comment by mcansh** [comment]
i was able to get it to work by calling fastify.removeContentParserType("application/json") before registering this plugin, i'll investigate if there's a different way to do it soon without end user configuration

**Comment by rolanday** [comment]
Thanks for the responsiveness! Indeed, calling removeContentTypeParser worked, which is counter-intuitive. Apologies. In you prev response, you essentially said to do this but I thought you were referring for me to "remove" the addContent Parser to try and work around.

Unfourtunatly, I'm stuck w/ issue that haven't been able to workaround:

```
.../node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5
    throw new TypeError(`${context} is not a ReadableStream.`);
          ^
TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (/Users/roland/GitHub/appyture/mkeg-web-app.proto-4-remix-fastify/node_modules/.pnp
```

I rings a bell please lmk, else I'll do my best to create a repo I can share, and create a separate ticket. I'm running into this when signing in using remix-auth oauth., but can't say for sure if related to remix-auth -- just know happens only when oauth'ing and repeatably so. There are many things in call stack when auth'ing -- db, redis, etc., but the call stack is not very helpful.

Thanks again for your help, and remix-fastify -- of course!

**Comment by mcansh** [comment]
this issue should suffice as i can reproduce locally with the example in this repo, i'll take a look at it this week

**Comment by rolanday** [comment]
Great to hear you can repro. Thank you, and I'll stay tuned. Super appreciated.

**Comment by rolanday** [comment]
Hi there and thank you! Sorry to say still seeing the issue, assuming we're talking about the ReadableStream exception. Please lmk if would like me to try and create a repro -- will take some effort but willing to.
