### ISSUE TITLE
Browser doesn't update with new code

### ISSUE THREAD

**Issue by woody146** [mcansh/remix-fastify#119]
Create file routes/test.tsx

```
export default function () {
  return <div>hello world</div>;
}
```

Then, I go to http://localhost:3000/test, it displays `hello world`. But I update file `test.tsx`, browser still displays old content

**Comment by pedrospj** [comment]
Can you provide a repo with your code so we can look package versions and code?

**Comment by mcansh** [comment]
i have a few hunches, i'm thinking of removing the plugin and moving everything to your server file (this can be done today), you can check out and try https://github.com/mcansh/remix-fastify/blob/c283b62a4c1ec51f19bd9e59651d3794e3e5024e/example/server.mjs

**Comment by woody146** [comment]
> Can you provide a repo with your code so we can look package versions and code?

You can check it https://github.com/woody146/remix-example
Go to http://localhost:3000/test, then update `routes/test.tsx`. I must press F5 to update page with new content 

It occurs same error when I test with `@remix-run/express` . So I think this error is from `remix-run`
