### ISSUE TITLE
the assetsBuildDirectory files do not get handled by the stricter handler (with immutable).

### ISSUE THREAD

**Issue by mcansh** [mcansh/remix-fastify#17]
I've tried to set the prefix to /build/ so they're correctly picked up, but I receive errors for double registration of routes then.

x-ref #16

**Comment by Jarrku** [comment]
I've currently resolved it for our project by doing the following:
`remix.config.js`
```ts
{
  assetsBuildDirectory: "build/public",
}
```

So they don't get emitted to the same `public` folder anymore as the other static assets, and then adjusting the first register call to:
```ts
await fastify.register(fastifyStatic, {
  root: fullOptions.assetsBuildDirectory,
  prefix: "/build/",
  wildcard: false,
  immutable: true,
  maxAge: "1y",
  dotfiles: "allow",
}); 
```

And calling the plugin with

```ts
await app.register(remixFastifyPlugin, {
  assetsBuildDirectory: path.resolve(process.cwd(), "build", "public"),
  build: serverBuild,
  mode: MODE,
  publicPath: "/build/",
});
```

But not sure how to resolve it when the assets are built into the regular `public` folder 😕

**Comment by mcansh** [comment]
got it working by opting out of the default serve behavior #18
