### ISSUE TITLE
Doesn't work with remix 1.5.1

### ISSUE THREAD

**Issue by ZiiMakc** [mcansh/remix-fastify#19]
With remix 1.5.1 root `GET` request will return empty html.

I was able to narrow it down to this piece of code
```
  if (Buffer.isBuffer(response.body)) {
    // in 1.4.3 this block was called, worked fine
    reply.send(response.body);
  } else if ((_response$body = response.body) !== null && _response$body !== void 0 && _response$body.pipe) {
    // in 1.5.1 this block not called because ` _response$body.pipe` is `undefined`
    response.body.pipe(reply.raw);
  } else {
    // in 1.5.1 this block is called and response body is empty
    reply.send();
  }
```

**Comment by mcansh** [comment]
heh yup, with the new fetch implementation we need to change a few things - stand by :)

**Comment by mcansh** [comment]
hahaha just spent way too long by using an actual app and it having cache-control and etags and was stumped for a solid 20 minutes on why it wasnt working 😅
