### ISSUE TITLE
Why is noopContentParser needed?

### ISSUE THREAD

**Issue by adaboese** [mcansh/remix-fastify#244]
```ts
const noopContentParser: FastifyContentTypeParser = (
  _request,
  payload,
  done,
) => {
  done(null, payload);
};

app.addContentTypeParser('application/json', noopContentParser);
app.addContentTypeParser('*', noopContentParser);
```

Just wondering what purpose this serves

**Comment by mcansh** [comment]
we don't want fasitfy to parse any formData from incoming requests, so we're just passing it through as is. the reason for both `json` and `*` being set is because `*` doesn't handle json for whatever reason

https://github.com/mcansh/remix-fastify/issues/116#issuecomment-1694540545

**Comment by mcansh** [comment]
> @mcansh Maybe the solution is to make `remix-fastify` work with [npmjs.com/package/fastify-raw-body](https://www.npmjs.com/package/fastify-raw-body) ?

the server is fully in your control, so you're able to use that already if you'd like.

Remix just needs the raw request body in order to parse it. i'm not sure if fastify has a way to only set the content parser for specific routes or not.

**Comment by mcansh** [comment]
without telling fastify to not process the json, it does, and that messes up things down the line. if you want to test out other ways to go about, i'm all for it. in the interim this works 

```js
app.addContentTypeParser("application/json", (req, payload, done) => {
  if (req.url === "/api/echo") {
    let body = "";
    req.raw.on("data", (chunk) => {
      body += chunk.toString();
    });
    req.raw.on("end", () => {
      let json = JSON.parse(body);
      return done(null, json);
    });
  }

  return done(null, payload);
});

app.addContentTypeParser(["text/plain", "*"], (request, payload, done) => {
  done(null, payload);
});

app.post("/api/echo", async (request, reply) => {
  let body = request.body;
  return reply.send(body);
});
```

**Comment by mcansh** [comment]
> I think that the ideal setup (given that this is a plugin for Fastify) is that `remix-fastify` should expect that parsing is already done at the Fastify level and Remix request is constructed using the parsed request.

this hasn't been a plugin for quite a while to allow for situations like this where you need more control over the server.
