### ISSUE TITLE
Add h2c support

### ISSUE THREAD

**Issue by adaboese** [mcansh/remix-fastify#254]
https://fastify.dev/docs/latest/Reference/HTTP2/

At the moment, if I set:

```
const app = fastify({
  http2: true,
});
```

Then when I am passing

```
const handler = createRequestHandler({..});

return handler(request, reply);
```

I am getting an error:

```
Argument of type 'FastifyRequest<RouteGenericInterface, Http2Server, Http2ServerRequest, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>' is not assignable to parameter of type 'FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>'.
  Type 'Http2ServerRequest' is missing the following properties from type 'IncomingMessage': headersDistinct, trailersDistinctts(2345)
(parameter) request: FastifyRequest<RouteGenericInterface, Http2Server, Http2ServerRequest, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>
```

Seems to be just type error.

**Comment by mcansh** [comment]
hey @adaboese, I just published an experimental version `0.0.0-experimental-227837d` which should allow you to use http2 in fastify :)

Let me know if you run into any issues and if not I'll merged and publish a stable release

**Comment by mcansh** [comment]
> Hey, as far as I can tell, this is working!

sweet thanks for confirming and using this 🙂

**Comment by mcansh** [comment]
> I am using this now in https://aimd.app/. To be honest, I don't completely know what's the difference. It is supposed to be faster, I think?

looks like you're using render as your web host which supports http2 by default without configuration. the changes in the pr should allow using http2/https locally or on a server that requires you to supply your own certificates that doesn't automatically give you http2/https.

**Comment by mcansh** [comment]
> > > I am using this now in https://aimd.app/. To be honest, I don't completely know what's the difference. It is supposed to be faster, I think?
> 
> > 
> 
> > looks like you're using render as your web host which supports http2 by default without configuration. the changes in the pr should allow using http2/https locally or on a server that requires you to supply your own certificates that doesn't automatically give you http2/https.
> 
> 
> 
> I am using Google Cloud (I used to use render.com – how do you know?). As far as I understand, the h2c is only for communication between Google Cloud Load Balancer and my docker container.

there's various services that'll tell you what tools, hosting, services, etc a website is using based on things in the dom, http headers, etc. i used wappalyzer and it still said render, but the server header said gcp 🤷‍♂️.
