### ISSUE TITLE
Failed running './server.js'

### ISSUE THREAD

**Issue by ChristopherDuda** [mcansh/remix-fastify#269]
I am trying to run the unstable-vite template and I am getting the following...

```
> dev
> cross-env NODE_ENV=development node --watch-path ./server.js --enable-source-maps ./server.js

(node:27007) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Failed running './server.js'
```

**Comment by mcansh** [comment]
what version of node are you using?

**Comment by ChristopherDuda** [comment]
18.14.1

**Comment by ChristopherDuda** [comment]
I can run the remix-run/remix/templates/unstable-vite-express without any issues, but I like fustily much better

**Comment by ChristopherDuda** [comment]
> > 18.14.1
> 
> ahh i switched to using `import.meta.dirname` recently, revert these lines in your server and you should be good to go. i'll revert the commit as well [04ad62e](https://github.com/mcansh/remix-fastify/commit/04ad62ed2816d0f8484147a4da692b5d5b01b26d)

This worked!  Thank you!
