### ISSUE TITLE
Update to stable Vite plugin

### ISSUE THREAD

**Issue by kibertoad** [mcansh/remix-fastify#281]
Remix has finally released stable Vite support: https://github.com/remix-run/remix/blob/main/CHANGELOG.md#v270

**Comment by kibertoad** [comment]
@mcansh documentation still refers to "unstable vite plugin", I believe that is no longer correct?..

**Comment by mcansh** [comment]
> @mcansh documentation still refers to "unstable vite plugin", I believe that is no longer correct?..

you're correct, i missed one usage of `unstable` 😅, thanks for the heads up
