### ISSUE TITLE
Question (Vite Remix example) Purpose of serving `build/client` directory?

### ISSUE THREAD

**Issue by Hoishin** [mcansh/remix-fastify#288]
The example of Vite Remix set up `@fastify/static` to serve the entire `build/client` directory in addition to `build/client/assets` regardless of `process.env.NODE_ENV`.

https://github.com/mcansh/remix-fastify/blob/69cd771a5565037dd31031070eae487af4426451/examples/vite/server.js#L43-L53

As far as I can tell, at least with Vite Remix setup, build command does not create additional files in `build/client` other than what's inside `build/client/assets` and it seems to be pointless. What is the purpose of this static serve setup?

**Comment by mcansh** [comment]
the build/client serving serves the files with a more lax caching setup of 1 hour and not setting the contents to be immutable whereas build/client/assets caches everything for a year and makes it immutable
