### ISSUE TITLE
Error importing @remix-run/dev/server-build in example

### ISSUE THREAD

**Issue by robmonie** [mcansh/remix-fastify#29]
When running remix using the example `server.ts` implementation provided [here](https://github.com/mcansh/remix-fastify/blob/main/example/server.ts) I get the following error on startup when it tries to import `@remix-run/dev/server-build`.

`Error: @remix-run/dev/server-build is not meant to be used directly from node_modules. It exists to provide type definitions for a virtual module provided by the Remix compiler at build time.`

From what I can tell this behaviour has been present in Remix for some time so i'm wondering whether i'm doing something wrong in my usage.

**Comment by mcansh** [comment]
@robmonie in order to use the server-build virtual module, you need to have remix build your server by setting https://github.com/mcansh/remix-fastify/blob/main/example/remix.config.js#L8, otherwise you can just import the build directly `import build from "./build"`

**Comment by robmonie** [comment]
Thanks @mcansh. That's helped. It looks like we had some misaligned config from how we'd initially bootstrapped our test app with an Express server.
