### ISSUE TITLE
Remix fastify setup questions

### ISSUE THREAD

**Issue by cliffordfajardo** [mcansh/remix-fastify#30]
After installing `remix-fastify` like so:

```
npm i @mcansh/remix-fastify
```

what are the next steps?
I took a look at your [`/example` folder](https://github.com/mcansh/remix-fastify/blob/main/example) and it looks the setup instructions would be like this:

1. Install a standard remix app like `Remix App Server`
2. Install  `npm i @mcansh/remix-fastify`
3. create a `server.ts` file at the root and use `@mcansh/remix-fastify`?

**Comment by mcansh** [comment]
Hey @cliffordfajardo, yes that should work, i think i started this example from the "express" template and just swapped out express deps for fastify

**Comment by mcansh** [comment]
just updated the readme with what i did for the example https://github.com/mcansh/remix-fastify/commit/4da25cbf3df0723275871c32a16f5a595a90eb11
