### ISSUE TITLE
hot reload

### ISSUE THREAD

**Issue by Coobaha** [mcansh/remix-fastify#33]
Hi thanks for you work with fastify integration. Please pardon me if I missed something but seems that hot reloading is not working for fastify server process? 

Express package creates remix handler on every request during dev 

https://github.com/remix-run/remix/blob/2a22a0f36638fa9c1c27580896cdd42d88a7d96d/packages/remix-serve/index.ts#L30-L33

**Comment by dalitroz** [comment]
I'm working on a PR for this. Should be ready today or tomorrow (and hopefully will be accepted ☺️).

**Comment by mcansh** [comment]
@dalitroz I'm down to see your implementation, but I've reconfigured some things to allow for this #43 (experimental build: `v0.0.0-experimental-29e3d11`) but there's a few things to do outside of hot reload in terms of public files (e.g /favicon.png isnt current working)

**Comment by dalitroz** [comment]
@mcansh I have just submitted the PR (https://github.com/mcansh/remix-fastify/pull/44) and I believe it includes the build dir change that you have in that commit. Please take a look, I believe it's a pretty comprehensive change. ☺️
