### ISSUE TITLE
How to handle errors thrown from the loader?

### ISSUE THREAD

**Issue by lilouartz** [mcansh/remix-fastify#356]
At the moment, this code:

```
import { defineLoader } from '#app/unstable';

export const loader = defineLoader(async () => {
  throw new Error('This is an error');
});
```

Produces this page:

https://pillser.com/checks/error

In Fastify, this is how I am handling it:

```ts
try {
  const handler = createRequestHandler({
    build: serverBuild,
    getLoadContext() {
      return {
        nonce: cspNonce,
        session: request.session as unknown as Session,
      };
    },
    mode: 'production',
  });

  return handler(request, reply);
} catch (error) {
  return reply.status(500).send('Internal Server Error');
}
```

How do I get Remix error page instead?

**Comment by lilouartz** [comment]
Also, while testing, I noticed that if I create route such as:

```ts
export default async () => {
  throw new Error('This is an error');
};
```

The error becomes:

```
Error: `line` must be greater than 0 (lines start at line 1)
```

This feels like a separate issue.

**Comment by mcansh** [comment]
> This feels like a separate issue.

I'll leave them together for now, and i'll open a new issue if it's not resolved by any changes from this one :)

**Comment by lilouartz** [comment]
@mcansh Any updates on this one?

**Comment by mcansh** [comment]
hey sorry for the slowness,  been busy with work. from what i can tell this is due to streaming with a pass through stream https://github.com/mcansh/remix-fastify/blob/main/packages/remix-fastify/src/server.ts#L134 - i'll investigate further soon

removing the pass through doesn't work in all instances

**Comment by mcansh** [comment]
i have an experimental release for you to try if you're still using this package :) 

`npm i @mcansh/remix-fastify@experimental` or `npm i @mcansh/remix-fastify@0.0.0-experimental-507702b`
