### ISSUE TITLE
throwing an Error in render results in `line` must be greater than 0 (lines start at line 1)

### ISSUE THREAD

**Issue by mcansh** [mcansh/remix-fastify#358]
```ts
export default function Component() {
  throw new Error('This is an error');
}
```

The error becomes:

```
Error: `line` must be greater than 0 (lines start at line 1)
```

This feels like a separate issue.

_Originally posted by @lilouartz in https://github.com/mcansh/remix-fastify/issues/356#issuecomment-2195857023_

**Comment by mcansh** [comment]
@lilouartz this is due to node's native source map support `--enable-source-maps` in the dev/start scripts - feel free to remove and use `source-map-support` [like before](https://github.com/mcansh/remix-fastify/pull/138/files) or remove source maps entirely

**Comment by lilouartz** [comment]
Hm. I am not actually using `--enable-source-maps` anywhere in my code.

**Comment by lilouartz** [comment]
I do use tsx, in case that could be related.

**Comment by mcansh** [comment]
> Hm. I am not actually using `--enable-source-maps` anywhere in my code.

not even in your package.json scripts? i removed that in my example test and it worked after that.

**Comment by lilouartz** [comment]
Yeah, no. However, I am reasonably sure this is due to `tsx`.

**Comment by mcansh** [comment]
> After some debugging, this turns out to be not an issue with `tsx`. I can replicate the same without it.

yeah i didnt think it was related to tsx as i was having the same issue with the `playground` example
