### ISSUE TITLE
tsm v. tsx

### ISSUE THREAD

**Issue by rolanday** [mcansh/remix-fastify#365]
Hello. I'm curious why you opted for tsm over tsx. I've been using tsx w/ remix fastify for some time (no issues), but have to assume you have good reasons for choosing tsm over tsx as is not actively maintained and sees far less usage than tsx (based on npm downloads). Or, in other words, what am I blissfully unaware that I'm giving up by using tsx? :-)

**Comment by mcansh** [comment]
no reason other than luke's projects are typically well maintained, lightweight, and work well. i didn't do a lot of research on different ts loaders for node, but the initial pr was for adding ts-node and i knew i didn't want to bring that as its none of those things from my experience. if you'd like to you're more than welcome to open a PR that switches over to tsx and i'd happily approve and merge 🙂

**Comment by rolanday** [comment]
+1 to not using ts-node. Happy to post a PR over the weekend -- it's just a package.json change to switch out the dep and tweak the dev script for tsx.

**Comment by rolanday** [comment]
https://github.com/mcansh/remix-fastify/commit/c7dbd5bd184bab9c3b7f9e13e6891b568a8f1fd2
