### ISSUE TITLE
Tree shaking not working

### ISSUE THREAD

**Issue by ziimakc** [mcansh/remix-fastify#386]
Tree shaking not working when running application using remix-fastify.

https://github.com/ziimakc/remix_tree_shaking

Steps to reproduce:
- run `pnpm i`
- run `pnpm build`
- run `pnpm start`
- open browser network tab and check for ~1mb package
- run `pnpm start:works`
-  open browser network tab and see that tree shaking works as expected with no packages more than ~0.1mb of size

**Comment by mcansh** [comment]
try setting NODE_ENV to production

**Comment by ziimakc** [comment]
@mcansh thanks, it works

**Comment by ozitrance** [comment]
Y
