### ISSUE TITLE
Remix: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by lilouartz** [mcansh/remix-fastify#395]
I am just wondering if you happen to know whether this is Remix issue or something specific with remix-fastify?

I described one of the ways to replicate it here:

https://github.com/remix-run/remix/discussions/9838

However, even after disabling the cache, I am still seeing occasional issues like this in Sentry.

I cannot find other Remix users experiencing this, which makes me wonder if this is specific to remix-fastify somehow?

Would you know how I could workaround this?

**Comment by mcansh** [comment]
i'll take a look when i get back to my personal computer 🙂

**Comment by lilouartz** [comment]
I am not 100% confident yet, but I am sure it is related to these:

* https://stackoverflow.com/questions/78883384/cannot-read-properties-of-null-reading-usememocache?noredirect=1#comment139079696_78883384
* https://github.com/lucide-icons/lucide/issues/2386

I am saying I am not 100% confident because as far as I recall, when I first reported this issue, I wasn't using React Compiler.

But posting here for context building.

**Comment by mcansh** [comment]
closing, but feel free to reopen if you run into any more issues
