### ISSUE TITLE
Using `getLoadContext` with the Vite version.

### ISSUE THREAD

**Issue by holmok-bestow** [mcansh/remix-fastify#404]
I like the Vite implementation with its short and sweet Fastify server code.

But my question is, how do I implement `getLoadContext`?

I see that `remixFastify` is a callable function, and I tried the following:

```
remixFastify(app, {
  getLoadContext: async (_, __) => {
    return { /*** add stuff ***/ }
  }
}, (error) => {
  app.log.error(error, 'server error')
})
```

But I can't get it to work. Is it possible? If so, do you have some sample code?

Thanks!

**Comment by holmok-bestow** [comment]
I even tried:

```
await app.register(remixFastify, {
  getLoadContext: async (_, __) => ({ /*** add stuff ***/ })
})
```

**Comment by mcansh** [comment]
im not sure what you mean. the second snippet is how you add `getLoadContext` with the plugin. then you can access that context in your loaders and actions via the `context` param that is passed to those

**Comment by holmok-bestow** [comment]
yeah... it does work if I `build` and `start` but for some (prolly unrelated reason) when I just `dev` I am getting this error.

```
[project path]/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:41127
  if (url.length === 0 || url[0] === '/') {
          ^


TypeError: Cannot read properties of undefined (reading 'length')
    at getProtohost ([project path]/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:41127:11)
    at Function.handle ([project path]/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:40978:19)
    at app ([project path]/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:40908:37)
    at Plugin.exec ([project path]/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin ([project path]/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.11.0
Failed running './server/index.ts'
```

**Comment by holmok-bestow** [comment]
...and deleting my `node_modules` and lock file and reinstalling dep fixed it, so never mind ...so sorry.


Thanks anyway for a great plugin!

**Comment by mcansh** [comment]
> ...and deleting my `node_modules` and lock file and reinstalling dep fixed it, so never mind ...so sorry.
> 
> 
> 
> 
> 
> Thanks anyway for a great plugin!

haha it's all good, happy to hear it's working 🥳
