### ISSUE TITLE
Latency after Loader

### ISSUE THREAD

**Issue by lilouartz** [mcansh/remix-fastify#412]
@mcansh Maybe it is something you are familiar...

<img width="1241" alt="Screenshot 2024-08-26 at 12 44 46 AM" src="https://github.com/user-attachments/assets/e1cc797e-8f04-400a-a3bd-d75fd0c62e1c">

I am trying to understand why my routes take +100ms to produce a response, despite loaders finishing all the work in under 30ms.

In screenshot you see a trace of https://pillser.com/supplements/vitamin-b1-3254. The loaders complete under ~30ms, but the `document_request` does not complete for another 100ms.

Just curious if it is something that you might have run into and know how to debug b/c our setups are similar?

**Comment by mcansh** [comment]
im not sure off hand, but i can try to look into it a bit on a couple of my apps

**Comment by lilouartz** [comment]
I am reasonably sure that this was happening because of under provisioning CPU.

I've increased allocation and this disappeared.

I made other changes though, so who knows for sure.

I am going to close as I don't think it is an issue with remix-fastify.

**Comment by mcansh** [comment]
sounds good! thanks for reporting back and if it creeps back let me know and i’ll take a look as well :)

**Comment by lilouartz** [comment]
Thank you :-)
