### ISSUE TITLE
useLoaderData() returns string value after recent update

### ISSUE THREAD

**Issue by philipp-spiess** [mcansh/remix-fastify#65]
I've been having some troubles in my small app after updating from `2.3.1` to `2.4.0`. I noticed that during route transitions, the loader data would no longer properly deserialize resulting in the `useLoaderData()` hook returning a string instead of the object.

This is really puzzeling part is that there is only one change in this library (https://github.com/mcansh/remix-fastify/commit/e2b42246fd115e3d1ea22e48c70ac0acd0bb14a4) which does not seem related to how the JSON payloads are handled _in the slightest_.

Yet, this is the diff that I can apply to reproduce the issue 🤔 It seems like no other transitive dependencies have changed for me either.

```diff
diff --git a/package.json b/package.json
index 9f72b25..493ff5c 100644
--- a/package.json
+++ b/package.json
@@ -14,7 +14,7 @@
   },
   "dependencies": {
     "@code-hike/lighter": "^0.3.4",
-    "@mcansh/remix-fastify": "2.3.1",
+    "@mcansh/remix-fastify": "2.4.0",
     "@prisma/client": "^4.10.0",
     "@radix-ui/react-dropdown-menu": "^2.0.2",
     "@radix-ui/react-tooltip": "^1.0.3",
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index 4ffca2e..4513092 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -2,7 +2,7 @@ lockfileVersion: 5.4
 
 specifiers:
   '@code-hike/lighter': ^0.3.4
-  '@mcansh/remix-fastify': 2.3.1
+  '@mcansh/remix-fastify': 2.4.0
   '@octokit/graphql-schema': ^13.2.0
   '@prisma/client': ^4.10.0
   '@radix-ui/react-dropdown-menu': ^2.0.2
@@ -34,7 +34,7 @@ specifiers:
 
 dependencies:
   '@code-hike/lighter': 0.3.4
-  '@mcansh/remix-fastify': 2.3.1_5gckvsvob3hapzq4izcu2nl2ve
+  '@mcansh/remix-fastify': 2.4.0_5gckvsvob3hapzq4izcu2nl2ve
   '@prisma/client': 4.10.0_prisma@4.10.0
   '@radix-ui/react-dropdown-menu': 2.0.2_5ndqzdd6t4rivxsukjv3i3ak2q
   '@radix-ui/react-tooltip': 1.0.3_5ndqzdd6t4rivxsukjv3i3ak2q
@@ -1948,8 +1948,8 @@ packages:
     engines: {node: '>=8'}
     dev: false
 
-  /@mcansh/remix-fastify/2.3.1_5gckvsvob3hapzq4izcu2nl2ve:
-    resolution: {integrity: sha512-gOeHayYhjgky4TxSaCUretrH03do4mwhgKRq8/OCRePie/S+66BfWsCHPIx3b4YjkrukfbqXK6qG8dYc/0BDUw==}
+  /@mcansh/remix-fastify/2.4.0_5gckvsvob3hapzq4izcu2nl2ve:
+    resolution: {integrity: sha512-JN4U48lPj3XGruNUvteIbc0h4ymdhb8UhQi5W5a5tnsl4vr7O4jwLXg4fRec33ptFdx4TkITgYr4TrZDbnqeEQ==}
     peerDependencies:
       '@remix-run/node': ^1.6.0
       fastify: ^3.29.0 || ^4.0.0
```

**Comment by philipp-spiess** [comment]
It does seem like the `content-type` headers are missing now. But I have no idea how this can relate to the commit I linked above 🤔 

## Before (`2.3.1`)

<img width="548" alt="Screenshot 2023-02-08 at 22 37 28" src="https://user-images.githubusercontent.com/458591/217656984-c1c66a2c-b686-4c37-a2a4-1ce873655259.png">

## After (`2.4.0 `)

<img width="796" alt="Screenshot 2023-02-08 at 22 38 17" src="https://user-images.githubusercontent.com/458591/217657074-81a4d9e9-00ed-4209-937e-6beec865519e.png">

**Comment by mcansh** [comment]
i'll take a peek, thanks for the report :)

**Comment by philipp-spiess** [comment]
@mcansh Thank you! I’m happy to help as well but I’m on an offsite this week so I won't get to it befor the weekend. For now I fixed it by pinning `2.3.1`.

**Comment by mcansh** [comment]
i published 2.4.1, which didn't change a whole lot other than you can opt out of purging the require cache if you're using `unstable_dev`, but that did make a difference in my brief test. do you have a public repo of this behavior? my example in the repo seems to be working fine now

**Comment by philipp-spiess** [comment]
`2.4.1` indeed works again. Very strange 😱 Were you able to reproduce the issue on `2.4.0`? Anyway since this issue is no longer reproduceable, I think we can close it. Thank you so much!

**Comment by mcansh** [comment]
i was actually, but didn't notice immediately as safari was still able to parse the loader data even without the content type being there. 

gonna add playwright here for a more complete integration test
