### ISSUE TITLE
Update to 1.2.1 with server.ts

### ISSUE THREAD

**Issue by ZiiMakc** [mcansh/remix-fastify#7]
Do you plan to update it?

**Comment by mcansh** [comment]
i'll update the example soon. the adapter itself should work just fine on 1.2.1, i have it in a few projects. is there something not working for you?

**Comment by ZiiMakc** [comment]
If I understood correctly, it now possible to define `server.ts` and it's will be compiled alongside remix. Correct me if I'm wrong.

**Comment by mcansh** [comment]
> If I understood correctly, it now possible to define `server.ts` and it's will be compiled alongside remix. Correct me if I'm wrong.

correct! i'll update the example later today

**Comment by mcansh** [comment]
example updated! https://github.com/mcansh/remix-fastify/commit/5bbec5812db6c321f5b4c430f78ba84a472760e0
